GET http://localhost:3000/

###
POST http://localhost:3000/signup
Content-Type: application/json

{
    "username": "yee cinn213",
    "password": "12345623",
    "email":"kobe0@gmail.com"
}


###
POST http://localhost:3000/loginUser
Content-Type: application/json

{
    "username": "yee cinn213",
    "password": "12345623",
    "email":"kobe0@gmail.com"
}


