GET http://localhost:3000/

###
POST http://localhost:3000/signup
Content-Type: application/json

{
    "username": "yee cinn213",
    "password": "12345623",
    "email":"kobe0@gmail.com"
}


###
POST http://localhost:3000/loginUser
Content-Type: application/json

{
    "username": "yee cinn213",
    "password": "12345623",
    "email":"kobe0@gmail.com"
}

//login user using value that is hardcoded into the database
###
POST http://localhost:3000/loginUser
Content-Type: application/json

{
    "username": "gg",
    "password": "34343",
    "email":"wee0@gmail.com"
}

